#pragma once

void default_constants();
void nextstate();

void drive_example();
void turn_example();
void drive_and_turn();
void wait_until_change_speed();
void swing_example();
void motion_chaining();
void combining_movements();
void interfered_example();
void odom_drive_example();
void odom_pure_pursuit_example();
void odom_pure_pursuit_wait_until_example();
void odom_boomerang_example();
void odom_boomerang_injected_pure_pursuit_example();
void measure_offsets();
void RedWP();
void Red5Ring();
void BlueWP();
void Blue3Ring();
void Skills();
void skills2();
void Red6Ring();
void Blue5Ring();
void RedRush();
void BlueRush();
void Redoneplusfive();
void BlueGoal();
void RedSigWP();
void Red4RingWP();
void Blue6Ring();
void BlueSigWP();
void RedGoal();
void RedWP_Pos();
void BlueWP_Pos();